### ISSUE TITLE
prepare data failed!

### ISSUE THREAD

**Issue by andyyuan78** [textclf/fancy-cnn#3]
drwxrwxr-x  2 envy envy     4096 Feb 10 17:32 wordvectors/
envy@ub1404envy:~/os_prj/github/fancy-cnn$ python prepare-imdb.py
INFO:**main**: Importing spaCy...
INFO:**main**: Initializing spaCy...
INFO:**main**: Checking data integrity...
Downloading IMDB dataset...
--2016-02-11 13:06:18--  http://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz
Resolving ai.stanford.edu (ai.stanford.edu)... 171.64.68.10
Connecting to ai.stanford.edu (ai.stanford.edu)|171.64.68.10|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://120.52.72.45:80/ai.stanford.edu/c3pr90ntcsf0/~amaas/data/sentiment/aclImdb_v1.tar.gz [following]
--2016-02-11 13:06:18--  http://120.52.72.45/ai.stanford.edu/c3pr90ntcsf0/~amaas/data/sentiment/aclImdb_v1.tar.gz
Connecting to 120.52.72.45:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 84125825 (80M) [application/x-gzip]
Saving to: ‘aclImdb_v1.tar.gz’

100%[===================================================================================================================================================================>] 84,125,825  54.7KB/s   in 35m 18s

2016-02-11 13:41:39 (38.8 KB/s) - ‘aclImdb_v1.tar.gz’ saved [84125825/84125825]

Unzipping...
Extracting...
Cleaning up...
Data tree in aclImdb.
INFO:**main**: Building word vectors from ./data/wv/IMDB-GloVe-300dim.txt
INFO:wordvectors.glove: Loading vectors from ./data/wv/IMDB-GloVe-300dim.txt
INFO:wordvectors.glove: Loading word 0
INFO:wordvectors.glove: Loading word 10000
INFO:wordvectors.glove: Loading word 20000
INFO:wordvectors.glove: Building storage structures...
INFO:wordvectors.glove: Mapping words to indices...
INFO:wordvectors.glove: Mapping indices to words...
INFO:wordvectors.glove: Loading word vector 0
INFO:wordvectors.glove: Loading word vector 10000
INFO:wordvectors.glove: Loading word vector 20000
INFO:wordvectors.glove: Normalizing vectors by norm...
INFO:**main**: Building global word vectors from ./data/wv/glove.42B.300d.120000.txt
INFO:wordvectors.glove: Loading vectors from ./data/wv/glove.42B.300d.120000.txt
INFO:wordvectors.glove: Loading word 0
Traceback (most recent call last):
  File "prepare-imdb.py", line 114, in <module>
    global_gb.build(zero_token=True, normalize_variance=False, normalize_norm=True)#.index()
  File "/home/envy/os_prj/github/fancy-cnn/wordvectors/glove.py", line 93, in build
    vectors[vals[0]] = [float(x) for x in vals[1:]]
ValueError: could not convert string to float: https://git-lfs.github.com/spec/v1
envy@ub1404envy:~/os_prj/github/fancy-cnn$ python prepare-yelp.py
INFO:**main**: Importing spaCy...
INFO:**main**: Initializing spaCy...
INFO:**main**: Building word vectors from ./data/wv/glove.42B.300d.120000.txt
INFO:wordvectors.glove: Loading vectors from ./data/wv/glove.42B.300d.120000.txt
INFO:wordvectors.glove: Loading word 0
Traceback (most recent call last):
  File "prepare-yelp.py", line 64, in <module>
    gb.build(zero_token=True).index()
  File "/home/envy/os_prj/github/fancy-cnn/wordvectors/glove.py", line 93, in build
    vectors[vals[0]] = [float(x) for x in vals[1:]]
ValueError: could not convert string to float: https://git-lfs.github.com/spec/v1
envy@ub1404envy:~/os_prj/github/fancy-cnn$

**Comment by lukedeo** [comment]
install `git-lfs` and `git lfs pull` before you try to run. That file is hosted on Git LFS, not on github
